version: '3.8'

services:
  db:
    image: "postgres:13"  # Use the PostgreSQL version you need
    container_name: postgres_db
    environment:
      POSTGRES_USER: llmlab 
      POSTGRES_PASSWORD: llmlab 
      POSTGRES_DB: llmlab 
    volumes:
      # - ./db_data:/var/lib/postgresql/data  # Persist database data
      - ./db:/docker-entrypoint-initdb.d  # Mount the backup directory
    ports:
      - "5442:5432"
# volumes:
#   db_data:
